CASOS_FALLIDOS = [
    ('054 — Producto con dos contracciones y dos libres', r"""A^{\mu\nu}_{\rho\sigma}B^{\rho}_{\mu}C^{\sigma}""", []),
    ('065 — Derivada contravariante de vector', r"""\partial^{\mu}(A_{\nu})""", [('μ', 'super'), ('ν', 'sub')]),
    ('066 — Derivada contravariante de vector contravariante', r"""\partial^{\mu}(A^{\nu})""", [('μ', 'super'), ('ν', 'super')]),
    ('070 — Derivada contravariante de tensor mixto', r"""\partial^{\lambda}(A^{\mu}_{\nu})""", [('λ', 'super'), ('μ', 'super'), ('ν', 'sub')]),
    ('072 — Derivada contraída contraria', r"""\partial^{\rho}(A_{\rho\mu})""", [('μ', 'sub')]),
    ('074 — Divergencia covariante', r"""\partial^{\mu}(A_{\mu})""", []),
    ('078 — Derivada de tensor mixto contraído', r"""\partial_{\rho}(A^{\mu}_{\rho\nu})""", [('μ', 'super'), ('ν', 'sub')]),
    ('082 — Segunda derivada contravariante', r"""\partial^{\mu}(\partial^{\nu}(A))""", [('μ', 'super'), ('ν', 'super')]),
    ('083 — Segunda derivada mixta', r"""\partial^{\mu}(\partial_{\nu}(A))""", [('μ', 'super'), ('ν', 'sub')]),
    ('084 — Laplaciano', r"""\partial^{\mu}(\partial_{\mu}(A))""", []),
    ('088 — Segunda derivada con contracción', r"""\partial^{\mu}(\partial_{\mu}(A_{\nu}))""", [('ν', 'sub')]),
    ('093 — Tercera derivada con contracción', r"""\partial^{\lambda}(\partial_{\mu}(\partial_{\lambda}(A)))""", [('μ', 'sub')]),
    ('094 — Tercera derivada completamente contraída', r"""\partial^{\lambda}(\partial^{\mu}(\partial_{\lambda}(A_{\mu})))""", []),
    ('099 — Cuatro derivadas con dos contracciones', r"""\partial^{\alpha}(\partial_{\beta}(\partial_{\alpha}(\partial^{\beta}(A))))""", []),
    ('100 — Derivadas mixtas con tensor', r"""\partial^{\alpha}(\partial_{\beta}(A^{\beta}_{\alpha\mu}))""", [('μ', 'sub')]),
    ('105 — Nabla contravariante', r"""\nabla^{\mu}(A_{\nu})""", [('μ', 'super'), ('ν', 'sub')]),
    ('110 — Divergencia covariante', r"""\nabla^{\mu}(A_{\mu})""", []),
    ('119 — Nabla doble contraída', r"""\nabla^{\mu}(\nabla_{\mu}(A))""", []),
    ('120 — Nabla doble sobre vector', r"""\nabla^{\mu}(\nabla_{\mu}(A_{\nu}))""", [('ν', 'sub')]),
    ('128 — Nabla de Laplaciano', r"""\nabla_{\lambda}(\partial^{\mu}(\partial_{\mu}(A)))""", [('λ', 'sub')]),
    ('129 — Derivada de Laplaciano', r"""\partial_{\lambda}(\partial^{\mu}(\partial_{\mu}(A)))""", [('λ', 'sub')]),
    ('130 — Nabla y derivada mixtas', r"""\nabla^{\lambda}(\partial_{\lambda}(A))""", []),
    ('131 — Derivada y nabla contraídas', r"""\partial^{\lambda}(\nabla_{\lambda}(A))""", []),
    ('132 — Nabla sobre derivada vectorial', r"""\nabla^{\lambda}(\partial_{\lambda}(A_{\mu}))""", [('μ', 'sub')]),
    ('133 — Derivada sobre nabla vectorial', r"""\partial^{\lambda}(\nabla_{\lambda}(A_{\mu}))""", [('μ', 'sub')]),
    ('134 — Nabla doble y derivada', r"""\nabla_{\lambda}(\partial^{\mu}(\partial_{\mu}(A)))""", [('λ', 'sub')]),
    ('135 — Derivada doble y nabla', r"""\partial_{\lambda}(\nabla^{\mu}(\nabla_{\mu}(A)))""", [('λ', 'sub')]),
    ('137 — Triple operador con vector', r"""\nabla_{\lambda}(\partial_{\mu}(\nabla^{\mu}(A^{\nu})))""", [('λ', 'sub'), ('ν', 'super')]),
    ('138 — Operadores completamente contraídos', r"""\nabla^{\lambda}(\partial_{\mu}(\nabla_{\lambda}(A^{\mu})))""", []),
    ('169 — Suma de Laplacianos', r"""\partial^{\mu}(\partial_{\mu}(A))+\partial^{\mu}(\partial_{\mu}(B))""", []),
    ('170 — Diferencia de Laplacianos', r"""\partial^{\mu}(\partial_{\mu}(A))-\partial^{\mu}(\partial_{\mu}(B))""", []),
    ('179 — Suma de productos escalares', r"""A^{\mu}B_{\mu}+C_{\nu}D_{\nu}+E^{\rho}F_{\rho}""", []),
    ('304 — Nabla doble contraída sobre producto', r"""\nabla^{\lambda}(\nabla_{\lambda}(A^{\mu}B_{\mu}))""", []),
    ('306 — Derivada doble contraída sobre producto', r"""\partial^{\lambda}(\partial_{\lambda}(A^{\mu}B_{\mu}))""", []),
    ('315 — Operador mixto completamente contraído', r"""\nabla^{\lambda}(\partial_{\mu}(A^{\mu}_{\lambda}B^{\rho}_{\rho}))""", []),
    ('316 — Operador mixto con libre', r"""\nabla^{\lambda}(\partial_{\mu}(A^{\mu}_{\rho}B^{\rho}_{\nu\lambda}))""", [('ν', 'sub')]),
    ('317 — Tres operadores', r"""\nabla_{\lambda}(\partial^{\mu}(\nabla_{\mu}(A_{\nu})))""", [('λ', 'sub'), ('ν', 'sub')]),
    ('318 — Tres operadores contraídos', r"""\nabla^{\lambda}(\partial_{\mu}(\nabla_{\lambda}(A^{\mu})))""", []),
    ('320 — Cuatro operadores con contracciones', r"""\nabla^{\alpha}(\partial_{\beta}(\nabla_{\alpha}(\partial^{\beta}(A))))""", []),
    ('322 — Dummy entre libres', r"""A_{\mu}B^{\nu}_{\mu\rho}""", [('ν', 'super'), ('ρ', 'sub')]),
    ('357 — Suma de Laplacianos', r"""\nabla^{\mu}(\nabla_{\mu}(A))+\nabla^{\mu}(\nabla_{\mu}(B))""", []),
    ('358 — Suma de operadores sobre vectores', r"""\nabla^{\mu}(\nabla_{\mu}(A_{\nu}))+\nabla^{\mu}(\nabla_{\mu}(B_{\nu}))""", [('ν', 'sub')]),
    ('359 — Suma de operadores sobre tensores', r"""\nabla^{\lambda}(\nabla_{\lambda}(A^{\mu}_{\nu}))-\nabla^{\lambda}(\nabla_{\lambda}(B^{\mu}_{\nu}))""", [('μ', 'super'), ('ν', 'sub')]),
    ('363 — Triple anidamiento', r"""\nabla_{\lambda}(\partial_{\mu}(\nabla^{\mu}(A_{\nu})))""", [('λ', 'sub'), ('ν', 'sub')]),
    ('364 — Triple anidamiento contraído', r"""\nabla^{\lambda}(\partial_{\mu}(\nabla_{\lambda}(A^{\mu})))""", []),
    ('365 — Triple anidamiento con dos libres', r"""\nabla_{\lambda}(\partial_{\mu}(\nabla^{\rho}(A^{\mu}_{\nu})))""", [('λ', 'sub'), ('ν', 'sub'), ('ρ', 'super')]),
]
